# Generated by Django 2.1.7 on 2019-02-16 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateField()),
                ('time_modified', models.TimeField()),
                ('price_updated', models.FloatField()),
                ('description_modified', models.TextField()),
                ('category_modified', models.TextField()),
                ('url_updated', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Game_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Game_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField()),
                ('save_state', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_the_game', models.TextField(max_length=140)),
                ('url_of_the_game', models.TextField()),
                ('price', models.FloatField()),
                ('date_added', models.DateField()),
                ('time_added', models.TimeField()),
                ('description', models.TextField()),
                ('category', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_purchased', models.DateField()),
                ('time_purchased', models.TimeField()),
                ('price_purchased', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_the_game', models.TextField(max_length=140)),
                ('price', models.FloatField()),
            ],
        ),
    ]
