# Generated by Django 2.1.7 on 2019-02-16 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gamestore', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_log',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchase',
            name='gameid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_gameid', to='gamestore.Games'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='games',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game_log',
            name='gameid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamelog_gameid', to='gamestore.Games'),
        ),
        migrations.AddField(
            model_name='game_log',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game_details',
            name='gameid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamedetails_gameid', to='gamestore.Games'),
        ),
        migrations.AddField(
            model_name='game_details',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admin_log',
            name='gameid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adminlog_gameid', to='gamestore.Games'),
        ),
        migrations.AddField(
            model_name='admin_log',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together={('userid', 'gameid')},
        ),
    ]
