# Generated by Django 2.1.5 on 2019-02-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0003_auto_20190215_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_log',
            name='price_updated',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='game_details',
            name='score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='games',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='price_purchased',
            field=models.FloatField(),
        ),
    ]
